---
version: "3.7"

services: 
  app:
    image: "node:current-alpine"
    working_dir: /home/node/app
    volumes:
      - ./node_modules:/home/node/app/node_modules:delegated
      - .:/home/node/app:consistent
    ports:
      - 3000
    environment:
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT
    entrypoint: "npm"

  test:
    image: "cypress/base:10"
    working_dir: /home/node/app
    volumes:
      - cache:/root/.cache
      - ./node_modules:/home/node/app/node_modules:delegated
      - .:/home/node/app:consistent
    environment:
      - API_HOST=$API_HOST
      - API_PORT=$API_PORT
    entrypoint: "./node_modules/.bin/cypress"

volumes:
  cache:
