version: "3.7"
services:
  "music-api":
    container_name: "music-api"
    image: "node:current-alpine"
    working_dir: /home/node/app
    ports:
      - 30000:30000
    environment:
      - VIRTUAL_HOST=albums.*
      - TZ=America/Central
    volumes:
      - type: bind
        source: "${PWD}/start-api.sh"
        target: /home/node/start.sh
    command: "sh /home/node/start.sh"

  "music-ui":
    container_name: "music-ui"
    image: "node:current-alpine"
    working_dir: /home/node/app
    environment:
      - TZ=America/Central
      - SERVER=192.168.100.2
      - PORT=30000
    ports:
      - 30100:30100
    depends_on:
      - "music-api" 
    volumes:
      - type: bind
        source: "${PWD}/start-ui.sh"
        target: /home/node/start.sh
    command: "sh /home/node/start.sh"
