version: "3.7"
services:
  "music-ui":
    container_name: "music-ui"
    image: "node:current-alpine"
    # user: "node"
    working_dir: /home/node/app
    environment:
      - VIRTUAL_HOST=albums.*
      - TZ=America/Central
    volumes:
      - type: bind
        source: "${PWD}/start.sh"
        target: /home/node/start.sh
    command: "sh /home/node/start.sh"
